### ISSUE TITLE
Postman collection for Hotel booking

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-action-bot#23] opened 2024-03-26 01:56 UTC
## Description

Create postman collection for the hotel booking use case details are as below
base_url - https://mit-ps-bap-client.becknprotocol.io
bap_id - mit-ps-bap.becknprotocol.io
bap_uri - https://mit-ps-bap.becknprotocol.io

Further details for registry , gateway , bpp are here - https://docs.google.com/spreadsheets/d/1X6RPNJH2eQrpjvHtZte9Jw6Zy0fIj7MNOcdlpr5iphE/edit#gid=2086670707

It should have, search, select, init confirm, cancel, and status endpoints.

Postman collection should be published under https://github.com/beckn/beckn-action-bot/artefacts/postman_collection

Link to catalogs sheet: https://fide-official.atlassian.net/wiki/spaces/DP/pages/293208066/Hotel+Catalog

## Goals

- [ ] Postman collection pointing to BAP protocol server.

## Expected Outcome

Postman collection for hotel use case that points to BAP protocol server.

## Acceptance Criteria

- [ ] All the listed endpoints must be there and the postman collection must be tested with BAP protocol server without any local services running.

**Comment by faizmagic** [comment] 2024-03-26 12:24
@zoyaashik< please provide an update

**Comment by faizmagic** [comment] 2024-03-27 12:55
Current update

1. Need to upload the catalogs
2. Following information are missing in the catalog sheet, but has been added to the bpp instance
    a. Fulfillments
          1. item fulfilment
          2. order fulfilment
          3. provider fulfilment
    b. Agent information
    c. cancellation terms
    d. payment information
    e. data for the support end points

@pri233, to assign this to another resource to get the catalogs updated in the confluence sheet
https://fide-official.atlassian.net/wiki/spaces/DP/pages/292356099/Tourism+Ticket+Booking+Catalog

**Comment by zoyaashik** [comment] 2024-03-28 05:11
The hotel domain in postman collection is yielding empty response for select endpoint. 
Debugging and troubleshooting the logs to find root cause

**Comment by zoyaashik** [comment] 2024-03-28 15:07
The root cause was provider image url in DB was too long. Hence shortenined url is updated. Created collection for search,select, init endpoints

**Comment by pri233** [comment] 2024-03-29 08:31
@em-abee  Plz get this closed asap

**Comment by mayurvir** [comment] 2024-04-01 04:36
Reviewed and merged, any issues discovered after this will be treated as separate bugs.

**Closed by mayurvir** 2024-04-01 04:36 UTC
Labels: enhancement
